CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL CHECK (nombre <> ''),
    prioridad INTEGER NOT NULL,
    descripcion text,
    fecha DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS taks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    nombre text NOT NULL CHECK (nombre <> ''),
    realizado BOOLEAN,
    projectid INTEGER REFERENCES projects(id)
);

SELECT * FROM projects;
SELECT projects.nombre WHERE projects.id = 2 AND(SELECT taks WHERE task.projectid = 2 AND )
SELECT * FROM taks;


/*TABLA PROJECTS*/
INSERT INTO projects (nombre, prioridad, descripcion , fecha) 
     VALUES ('JavaScript course', 1 , 'Curso Api con Javascript', '2019-10-10')

INSERT INTO projects (nombre, prioridad, descripcion, fecha)
     VALUES ('Python course', 2, 'SDN con python y Mininet', '2019-10-12')


/*TABLA TAKS*/
INSERT INTO taks (nombre, realizado, projectId) 
     VALUES ('Donwload course JavaScript', false , 1)

INSERT INTO taks (nombre, realizado, projectId) 
     VALUES ('Donwload course Python', false , 2)